# -*- coding: utf-8 -*-
"""DreamStudio_Crawling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17y6sfGOV-0AVlzGB1t7jZF9Y3lTueNUg
"""

!pip install selenium
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

import time
import json
import os
import re
import tempfile


# 크롬 드라이버 실행
temp_dir = tempfile.mkdtemp()

options = Options()
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
options.add_argument(f'--user-data-dir={temp_dir}')

driver = webdriver.Chrome(options=options)


# 예약 페이지로 이동
driver.get("https://www.xn--hy1bm6g6ujjkgomr.com/bbs/board.php?bo_table=booking&cp_code=&mode=orderform&rm_ix=25")

# 2초 정도 대기 (캘린더 로딩 시간)
time.sleep(2)

# 날짜 클릭 (예: 2025-04-10)
target_date = "2025-04-10"
xpath_expr = f'//div[contains(@id, "{target_date}_day")]'
target_element = WebDriverWait(driver, 10).until(
    EC.presence_of_element_located((By.XPATH, xpath_expr))
)
target_element.click()

# 정보가 갱신되도록 잠깐 기다림
time.sleep(2)  # 또는 WebDriverWait로 바꿔도 좋아

# time-list (ul 태그)가 뜰 때까지 기다림
WebDriverWait(driver, 10).until(
    EC.presence_of_element_located((By.ID, "time-list"))
)

# ul#time-list 안의 모든 label.btn-time 요소들 찾기
time_labels = driver.find_elements(By.CSS_SELECTOR, "#time-list label.btn-time")

# 각 label의 title 속성 추출
available_times = [label.get_attribute("title") for label in time_labels]

# 출력
print("예약 가능 시간 목록:")
for time in available_times:
    print(time)

driver.quit()